### ISSUE TITLE
Build error: ‘isWindowsLargePageBroken’ was not declared in this scope

### ISSUE THREAD

**Issue by dbermond** [vapoursynth/vapoursynth#376]
I'm getting the following error when trying to compile VapourSynth:
```
CXX      src/core/libvapoursynth_la-vscore.lo
src/core/vscore.cpp: In member function ‘void* MemoryUse::allocateLargePage(size_t) const’:
src/core/vscore.cpp:331:29: warning: suggest parentheses around ‘+’ in operand of ‘&’ [-Wparentheses]
     allocBytes = allocBytes + (granularity - 1) & ~(granularity - 1);
                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
src/core/vscore.cpp: In destructor ‘MemoryUse::~MemoryUse()’:
src/core/vscore.cpp:485:29: error: ‘isWindowsLargePageBroken’ was not declared in this scope
     if (largePageEnabled && isWindowsLargePageBroken())
                             ^~~~~~~~~~~~~~~~~~~~~~~~
src/core/vscore.cpp: In member function ‘bool VSCore::loadAllPluginsInPath(const string&, const string&)’:
src/core/vscore.cpp:1161:38: warning: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Wdeprecated-declarations]
         readdir_r(dir, entry, &result);
                                      ^
In file included from src/core/vscore.cpp:26:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
make: *** [Makefile:1527: src/core/libvapoursynth_la-vscore.lo] Error 1
```

I git bisect shows that it is caused by commit df691fa5e6b4911b0cc096c3ad923c57488927f9.

I can confirm that is was building fine until commit 4b6bdaac7e4c6d2bf449d96c8b273565e47957ba.

**System Information:**
**OS:** Arch Linux x86_64
**Compiler:** gcc 7.3.1
**VapourSynth:** git master

**Comment by begna112** [comment]
I can also confirm this issue and that building up to commit 4a6bd15 works. Anything after that fails.

**Comment by dbermond** [comment]
I can confirm that it's building fine now after the fix.

Thank you for fixing this!
