### ISSUE TITLE
Building error with zimg

### ISSUE THREAD

**Issue by dbermond** [vapoursynth/vapoursynth#332]
I'm getting this error when running the configure script:
```
checking for zimg... yes
configure: error: failed to link zimg. See config.log for details.
```

The relevant part of `config.log` shows:
```
configure:17552: checking for zimg
configure:17559: $PKG_CONFIG --exists --print-errors "zimg"
configure:17562: $? = 0
configure:17576: $PKG_CONFIG --exists --print-errors "zimg"
configure:17579: $? = 0
configure:17637: result: yes
configure:17673: g++ -o conftest -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now conftest.cpp -lzimg >&5
conftest.cpp:30:2: error: #error zimg API v2.3 or greater required
 #error zimg API v2.3 or greater required
  ^~~~~
configure:17673: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "vapoursynth"
| #define PACKAGE_TARNAME "vapoursynth"
| #define PACKAGE_VERSION "39"
| #define PACKAGE_STRING "vapoursynth 39"
| #define PACKAGE_BUGREPORT "https://github.com/vapoursynth/vapoursynth/issues"
| #define PACKAGE_URL "http://www.vapoursynth.com/"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_FSEEKO 1
| #define NDEBUG 1
| #define VS_TARGET_OS_LINUX 1
| #define VS_TARGET_CPU_X86 1
| #define VS_CORE_EXPORTS 1
| /* end confdefs.h.  */
| 
| #include <zimg.h>
| 
| #if ZIMG_API_VERSION < ZIMG_MAKE_API_VERSION(2, 3)
| #error zimg API v2.3 or greater required
| #endif
| 
| int
| main ()
| {
| 
| unsigned major, minor, micro;
| zimg_get_version_info(&major, &minor, &micro);
| 
| 
|   ;
|   return 0;
| }
configure:17676: error: failed to link zimg. See config.log for details.
```

I can confirm that it was building fine until commit ccca638d0cee0c977a8a87e53e792e15b1cec927.

A git bisect shows that is being caused by commit bc60aebd05ec174d05f9a5463d2ec3e5a7531e18.

**Steps to reproduce:**
```
$ git clone https://github.com/vapoursynth/vapoursynth.git vapoursynth-git
$ cd vapoursynth-git
$ ./autogen.sh
$ ./configure --prefix='/usr'
```

**System information:**
**OS:** Arch Linux x86_64
**vapoursynth:** git master (currently at r38.54.ge98ea74)
**zimg:** 2.5.1

**Comment by dubhater** [comment]
You need a newer zimg. I flagged the package.

**Comment by dbermond** [comment]
Shouldn't zimg 2.5.1 be suficcient to build since the minimum required version is 2.3?

**Comment by dubhater** [comment]
The error message is talking about the API version, which is not related to the project's version.

zimg version 2.5 provides zimg API version 2.2.
zimg version 2.6 provides zimg API version 2.3.

I can explain further if you want.

**Comment by dbermond** [comment]
Understood.
It works when trying with zimg git master.

This can be closed since there is nothing wrong with vapoursynth.
Thank you for the replies and for the attention!
