### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by animetosho** [vapoursynth/vapoursynth#298]
`--enable-debug` configure option doesn't seem to work with GCC 4.9.2, I get a whole lot of errors like the following:

~~~
src/core/genericfilters.cpp:820:129: error: the last argument must be an 8-bit immediate
                 __m128i m3 = _mm_or_si128(_mm_andnot_si128(tailmask, _mm_srli_si128(m2, sizeof(T))), _mm_and_si128(tailmask, m1));
                                                                                                                                 ^
src/core/genericfilters.cpp:823:129: error: the last argument must be an 8-bit immediate
                 __m128i b3 = _mm_or_si128(_mm_andnot_si128(tailmask, _mm_srli_si128(b2, sizeof(T))), _mm_and_si128(tailmask, b1));
                                                                                                                                 ^
src/core/genericfilters.cpp:841:101: error: the last argument must be an 8-bit immediate
                 __m128i t1 = _mm_or_si128(_mm_and_si128(t3, leadmask), _mm_slli_si128(t2, sizeof(T)));
~~~

Seems like it doesn't like folding sizeof to an immediate for some reason: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59071 Perhaps a bug in GCC, but thought I'd mention it anyway.

Is there a way to get debugging symbols without disabling optimisations (for diagnosing crashes), or is this already included in the standard compile?

---

Compilation (Cython) seems to fail with Python 3.4.2 installed as f strings aren't supported. I reverted those relevant changes from [these](https://github.com/vapoursynth/vapoursynth/commit/ff94b3424567ff84b64917aafca03b4258d73daa) [two](https://github.com/vapoursynth/vapoursynth/commit/f681828e4d65e4b829e1cd65983d49da09ceb56a) commits to use string concatenation, and it seems to work, but the documentation says [any version of Python 3 will do](http://www.vapoursynth.com/doc/installation.html#linux-and-os-x-compilation-instructions). Is this still the case or is Python 3.6 now a requirement?

Also, I had to upgrade Cython as it wouldn't recognise cpdef (0.21.1 didn't work, but 0.25.2 did). Just thought it might be worth pointing out, if you wanted to add some note about it to the documentation.

Thanks for reading!

**Comment by myrsloik** [comment]
1. It's a well known GCC bug, get a newer GCC/whatever
2. All modern Python versions are supported. I think 3.3 (or maybe 3.2) is the lowest actually working. Cython handles the f-strings so they're Python version independent but do require a recent Cython

**Comment by Kamekameha** [comment]
Yeah, Cython 0.24 is now required to generate the python module. I did state that when I submitted the relevant PR.

**Comment by animetosho** [comment]
Ah I see, didn't know that.  
Thanks a lot for the very quick response + info!
